//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weekc.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("weekc.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutItem {
            get {
                return ResourceManager.GetString("AboutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string AccentColorBlue {
            get {
                return ResourceManager.GetString("AccentColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brown.
        /// </summary>
        public static string AccentColorBrown {
            get {
                return ResourceManager.GetString("AccentColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string AccentColorGreen {
            get {
                return ResourceManager.GetString("AccentColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accent color.
        /// </summary>
        public static string AccentColorLabel {
            get {
                return ResourceManager.GetString("AccentColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lime.
        /// </summary>
        public static string AccentColorLime {
            get {
                return ResourceManager.GetString("AccentColorLime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magenta.
        /// </summary>
        public static string AccentColorMagenta {
            get {
                return ResourceManager.GetString("AccentColorMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mango.
        /// </summary>
        public static string AccentColorMango {
            get {
                return ResourceManager.GetString("AccentColorMango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pink.
        /// </summary>
        public static string AccentColorPink {
            get {
                return ResourceManager.GetString("AccentColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purple.
        /// </summary>
        public static string AccentColorPurple {
            get {
                return ResourceManager.GetString("AccentColorPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string AccentColorRed {
            get {
                return ResourceManager.GetString("AccentColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teal.
        /// </summary>
        public static string AccentColorTeal {
            get {
                return ResourceManager.GetString("AccentColorTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the color.
        /// </summary>
        public static string AccountsChooseTitle {
            get {
                return ResourceManager.GetString("AccountsChooseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        public static string AllDayLabel {
            get {
                return ResourceManager.GetString("AllDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attendees.
        /// </summary>
        public static string AttendeesItem {
            get {
                return ResourceManager.GetString("AttendeesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a BETA VERSION released for testing purposes. To send comments, tap the feedback and support button. Thank you for testing this product..
        /// </summary>
        public static string BetaLabel {
            get {
                return ResourceManager.GetString("BetaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar:.
        /// </summary>
        public static string CalendarLabel {
            get {
                return ResourceManager.GetString("CalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Francesco Martire..
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day begins at.
        /// </summary>
        public static string DayBeginsLabel {
            get {
                return ResourceManager.GetString("DayBeginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day ends at.
        /// </summary>
        public static string DayEndsLabel {
            get {
                return ResourceManager.GetString("DayEndsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsItem {
            get {
                return ResourceManager.GetString("DetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPOINTMENT.
        /// </summary>
        public static string DetailsTitleAppointment {
            get {
                return ResourceManager.GetString("DetailsTitleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEETING.
        /// </summary>
        public static string DetailsTitleMeeting {
            get {
                return ResourceManager.GetString("DetailsTitleMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User reviews are important: if you have any problem or complaint, please send me an email before to give Week Calendar a low rate..
        /// </summary>
        public static string LimitationsLabel {
            get {
                return ResourceManager.GetString("LimitationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran Week Calendar. Would you like to send an email to report it? The message is auto generated and will help the author to remove the bug..
        /// </summary>
        public static string LittleWatsonMessage {
            get {
                return ResourceManager.GetString("LittleWatsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Report.
        /// </summary>
        public static string LittleWatsonTitle {
            get {
                return ResourceManager.GetString("LittleWatsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no title).
        /// </summary>
        public static string NoTitleLabel {
            get {
                return ResourceManager.GetString("NoTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting organizer.
        /// </summary>
        public static string OrganizerLabel {
            get {
                return ResourceManager.GetString("OrganizerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (personal).
        /// </summary>
        public static string PrivateLabel {
            get {
                return ResourceManager.GetString("PrivateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string SearchAccountsLabel {
            get {
                return ResourceManager.GetString("SearchAccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH ON THESE ACCOUNTS.
        /// </summary>
        public static string SearchAccountsTitle {
            get {
                return ResourceManager.GetString("SearchAccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap the search icon, type a string and press enter..
        /// </summary>
        public static string SearchDefaultText {
            get {
                return ResourceManager.GetString("SearchDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no appointments found. tap the search icon, type a string and press enter..
        /// </summary>
        public static string SearchNoAppts {
            get {
                return ResourceManager.GetString("SearchNoAppts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string SearchRangeLabel {
            get {
                return ResourceManager.GetString("SearchRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last 3 months.
        /// </summary>
        public static string SearchRangeLast3 {
            get {
                return ResourceManager.GetString("SearchRangeLast3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next 3 months.
        /// </summary>
        public static string SearchRangeNext3 {
            get {
                return ResourceManager.GetString("SearchRangeNext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this month.
        /// </summary>
        public static string SearchRangeThisMonth {
            get {
                return ResourceManager.GetString("SearchRangeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the string to search for.
        /// </summary>
        public static string SearchStringLabel {
            get {
                return ResourceManager.GetString("SearchStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsItem {
            get {
                return ResourceManager.GetString("SettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show private appointments.
        /// </summary>
        public static string ShowPrivateLabel {
            get {
                return ResourceManager.GetString("ShowPrivateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weekends.
        /// </summary>
        public static string ShowWeekendsLabel {
            get {
                return ResourceManager.GetString("ShowWeekendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show week number.
        /// </summary>
        public static string ShowWeekNumberLabel {
            get {
                return ResourceManager.GetString("ShowWeekNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.
        /// </summary>
        public static string StoreLabel {
            get {
                return ResourceManager.GetString("StoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail the author.
        /// </summary>
        public static string SupportLabel {
            get {
                return ResourceManager.GetString("SupportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of the live tile on homescreen..
        /// </summary>
        public static string TaskLabel {
            get {
                return ResourceManager.GetString("TaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayButton {
            get {
                return ResourceManager.GetString("TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TranslationLabel {
            get {
                return ResourceManager.GetString("TranslationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial version has expired. If you liked this application, support its development buying it on the Store..
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last trial run..
        /// </summary>
        public static string TrialLast {
            get {
                return ResourceManager.GetString("TrialLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} trial runs left..
        /// </summary>
        public static string TrialLeft {
            get {
                return ResourceManager.GetString("TrialLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a licensed version: thank you for supporting this app! Do you find it useful? Then spread the word all around! :-).
        /// </summary>
        public static string TrialLicensed {
            get {
                return ResourceManager.GetString("TrialLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one trial run left..
        /// </summary>
        public static string TrialOne {
            get {
                return ResourceManager.GetString("TrialOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proceed with trial.
        /// </summary>
        public static string TrialProceed {
            get {
                return ResourceManager.GetString("TrialProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a full featured trial version. If you like it, support its development buying it on the Store..
        /// </summary>
        public static string TrialText {
            get {
                return ResourceManager.GetString("TrialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string WeekShortLabel {
            get {
                return ResourceManager.GetString("WeekShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom.
        /// </summary>
        public static string ZoomButton {
            get {
                return ResourceManager.GetString("ZoomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom on start.
        /// </summary>
        public static string ZoomOnStartLabel {
            get {
                return ResourceManager.GetString("ZoomOnStartLabel", resourceCulture);
            }
        }
    }
}
